CREATE TABLE contacts(
 id INT AUTO_INCREMENT PRIMARY KEY,
 contact_name VARCHAR(255) NOT NULL,
contact_email VARCHAR(255) NOT NULL,
phone_number VARCHAR(20) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);